/** code generated by Kinyoshi */
package net.minecraft.src;

import java.io.*;
import java.util.*;
import net.minecraft.client.Minecraft;

public class mod_DesertGrund extends BaseMod
{
	public mod_DesertGrund()
	{

		readWriteProperties();

        BlockGrundPlant = (new BlockGrundPlant(BlockGrundPlantID)).setHardness(0.1F).setResistance(0.1F).setLightValue(0.0F).setStepSound(Block.soundGrassFootstep).setUnlocalizedName("BlockGrundPlant");
        ModLoader.addName(BlockGrundPlant, "Grund Plant");
        BlockGrundPlantTop = (new BlockGrundPlantTop(BlockGrundPlantTopID)).setHardness(0.2F).setResistance(0.1F).setLightValue(0.0F).setStepSound(Block.soundGrassFootstep).setUnlocalizedName("BlockGrundPlantTop");
        ModLoader.addName(BlockGrundPlantTop, "Grund Plant");
    }

	public void readWriteProperties() {
		Properties properties = new Properties();
		try
		{
            File file = new File((new StringBuilder()).append(Minecraft.getMinecraftDir()).append("/mods/DesertGrundPlant.config").toString());
            boolean flag = file.createNewFile();
            if(flag)
            {
                FileOutputStream fileoutputstream = new FileOutputStream(file);
                properties.setProperty("BlockGrundPlantID", Integer.toString(255));
                properties.setProperty("BlockGrundPlantTopID", Integer.toString(250));
                properties.store(fileoutputstream, "Change the ID's to fix ID incompatibilities.");
                fileoutputstream.close();
            }
            properties.load(new FileInputStream((new StringBuilder()).append(Minecraft.getMinecraftDir()).append("/mods/DesertGrundPlant.config").toString()));
            BlockGrundPlantID = Integer.parseInt(properties.getProperty("BlockGrundPlantID"));
            BlockGrundPlantTopID = Integer.parseInt(properties.getProperty("BlockGrundPlantTopID"));
        }
        catch(IOException ioexception)
        {
            ioexception.printStackTrace();
            BlockGrundPlantID = 255;
            BlockGrundPlantTopID = 250;
        }
	}

    public void generateSurface(World var1, Random var2, int var3, int var4)
    {
    	    //cluster
        for (int var5 = 0; var5 < var2.nextInt(3) + 1; ++var5)
        {
            int var6 = var3 + var2.nextInt(16) + 2;
            int var7 = var2.nextInt(128);
            int var8 = var4 + var2.nextInt(16) + 2;
            (new WorldGenDesertGrund()).generate(var1, var2, var6, var7, var8);
        }
    }

    public class WorldGenDesertGrund extends WorldGenerator
{
    public boolean generate(World var1, Random var2, int var3, int var4, int var5)
    {
    //	vein size
        for (int var6 = 0; var6 < var2.nextInt(2) + 1; ++var6) //1
        {
            int var7 = var3 + var2.nextInt(16) - var2.nextInt(2);
            int var8 = var4;
            int var9 = var5 + var2.nextInt(16) - var2.nextInt(2);

            if (var1.isAirBlock(var7, var4, var9) && (var1.getBlockMaterial(var7 - 1, var4 - 1, var9) == Material.sand || var1.getBlockMaterial(var7 + 1, var4 - 1, var9) == Material.sand || var1.getBlockMaterial(var7, var4 - 1, var9 - 1) == Material.sand || var1.getBlockMaterial(var7, var4 - 1, var9 + 1) == Material.sand))
            {

                  // spawn height
                for (int var11 = 0; var11 < var2.nextInt(2) + 1; ++var11)
                {
                    if (BlockGrundPlant.canBlockStay(var1, var7, var8 + var11, var9))
                    {
                        var1.setBlock(var7, var8 + var11, var9, BlockGrundPlant.blockID);
                    }
                }
            }
        }

        return true;
    }
}

	public String getVersion() {
		return "MineCraft1.5.2__DesertGrund1.5.2r1";
	}

    public static Block BlockGrundPlant;
    public static int BlockGrundPlantID;
    public static Block BlockGrundPlantTop;
    public static int BlockGrundPlantTopID;

	public void load()
	{
        ModLoader.registerBlock(BlockGrundPlant);
        ModLoader.registerBlock(BlockGrundPlantTop);
	}
}
